engines:
  radon:
    enabled: true
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
    checks:
      bug:
        enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "tlslite/**"
  - "**.py"
exclude_paths:
 - "tests/**/*"
 - "scripts/**/*"
 - "unit_tests/**/*"
